### PR TITLE
Add `outLength` to full API, tells caller how many samples were written

### PR DESCRIPTION
**Pull request by tortis**
Includes both number of frames and number of samples for convenience and to avoid confusion.

Real-world example usage:

```typescript
const outLength = {frames: 0, samples: 0};
resampler.full(res.samples, sampleBuffer, outLength);
res.samples = sampleBuffer.slice(0, outLength.samples);
```

Ref #143

### CODE REVIEW

**Comment by aolsenjazz** [comment]
I'm glad that you brought up the idea of frames. It seems truer to implementation of SRC internally to use frames rather than samples. Would you revise to just use frames? Again, thanks for suggesting that.

**Comment by tortis** [comment]
Sounds good, I amended the commit, so it just has frames now.

**Comment by aolsenjazz** [comment]
Thanks - 1 more step. I had to update node version in CI for tests to pass - would you merge with main and update to 2.1.2? I'll publish on NPM and worry about test coverage when I have some time.

Thanks for the extra time.

**Comment by tortis** [comment]
I rebased the upstream, and ran `npm version 2.1.2`.
I can't push the tag to the upstream, if you wanna keep version tags, so I'll leave that to you.

Thanks for helping get this change out!

**Pull request merged**
